# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('EN', 'English'), ('BN', 'Bengali'), ('HI', 'Hindi'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('ML', 'Malayalam'), ('MR', 'Marathi'), ('FR', 'French')], max_length=2)),
                ('run_length', models.IntegerField(help_text='Enter run length in minutes')),
                ('certificate', models.CharField(choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=2)),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
