# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160806_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity_index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
